# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: check-added-large-files
  - id: check-merge-conflict

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.4
  hooks:
  - id: ruff
    args: [ --fix ]
  - id: ruff-format

- repo: https://github.com/Artalus/pre-commit-mypy
  rev: v0.2
  hooks:
  - id: mypy

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.29.2
  hooks:
  - id: check-github-workflows
    args: ["--verbose"]
