name: ci kinda

on:
  push:
    branches: [ "main", "mq/stage" ]
  pull_request:
    branches: [ "main" ]

permissions:
  actions: 'write'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - if: contains(github.event.pull_request.labels.*.name, 'qram-enqueued')
      run: |
        gh run cancel ${{ github.run_id }}
        gh run watch ${{ github.run_id }}
      env:
        GH_TOKEN: ${{ github.token }}

    - uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: lint with ruff
      run: ruff src

    - name: unit tests
      run: pytest test/unit/ test/component/ --cov
    - name: upload unit coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        flags: unit

    - name: integration tests
      run: pytest test/integration/ --cov
    - name: upload integration coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        flags: integration

    - name: system tests (A)
      if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      run: |
        pytest \
          -o log_cli=1 \
          --log-cli-level=DEBUG \
          --log-cli-format='%(asctime)s %(levelname)-6s :: %(name)-25s :: %(message)s' \
          test/system/ \
          -m sysA \
          --cov
      env:
        QRAM_APP_HMAC: ${{ secrets.QRAM_APP_HMAC }}
        QRAM_APP_GITHUB_APP_ID: ${{ secrets.QRAM_APP_GITHUB_APP_ID }}
        QRAM_APP_GITHUB_INSTALLATION_ID: ${{ secrets.QRAM_APP_GITHUB_INSTALLATION_ID }}
        QRAM_APP_GITHUB_PEM: ${{ secrets.QRAM_APP_GITHUB_PEM }}
        QRAM_WEBHOOK_URL: ""
    - name: upload system coverage to Codecov
      if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        flags: system-a


  system-test-with-webhook:
    needs: ci
    runs-on: ubuntu-latest
    # hardcore system tests reconfigure github app webhook to use local ngrok tunnel,
    # so no more than one instance of those should be running at once
    concurrency: app-webhook-reconfiguration
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: download ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar -xf ngrok-v3-stable-linux-amd64.tgz
        chmod +x ngrok
    - name: system tests (B)
      run: |
        ./ngrok http 8888 &
        sleep 5
        URL=$(scripts/ngrok-public-url.py)

        echo "QRAM_WEBHOOK_URL=${URL}/webhook" > .env
        pytest \
          -o log_cli=1 \
          --log-cli-level=DEBUG \
          --log-cli-format='%(asctime)s %(levelname)-6s :: %(name)-25s :: %(message)s' \
          test/system/ \
          -m sysB \
          --cov
      env:
        QRAM_APP_HMAC: ${{ secrets.QRAM_APP_HMAC }}
        QRAM_APP_GITHUB_APP_ID: ${{ secrets.QRAM_APP_GITHUB_APP_ID }}
        QRAM_APP_GITHUB_INSTALLATION_ID: ${{ secrets.QRAM_APP_GITHUB_INSTALLATION_ID }}
        QRAM_APP_GITHUB_PEM: ${{ secrets.QRAM_APP_GITHUB_PEM }}
    - name: upload system coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        flags: system-b
