name: ci kinda

on:
  push:
    branches: [ "main", "mq/stage" ]
  pull_request:
    branches: [ "main" ]

permissions:
  actions: 'write'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - if: contains(github.event.pull_request.labels.*.name, 'qram-enqueued')
      run: |
        gh run cancel ${{ github.run_id }}
        gh run watch ${{ github.run_id }}
      env:
        GH_TOKEN: ${{ github.token }}

    - uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: lint with ruff
      run: ruff src

    # need this to detect cases where git commands require user and would fail without one
    - name: wipe git user config
      run: |
        set -ex
        git config user.name
        git config user.name ""
        git config user.email
        git config user.email ""

    - name: unit tests
      run: |
        pytest test/unit/ test/component/ --cov --cov-report xml
        mkdir coverage
        mv coverage.xml coverage/unit.xml

    - name: integration tests
      run: |
        pytest test/integration/ --cov --cov-report xml
        mv coverage.xml coverage/integration.xml

    - name: system tests (A)
      if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      run: |
        pytest \
          -o log_cli=1 \
          --log-cli-level=DEBUG \
          --log-cli-format='%(asctime)s %(levelname)-6s :: %(name)-25s :: %(message)s' \
          test/system/ \
          -m sysA \
          --cov \
          --cov-report xml
        mv coverage.xml coverage/system.a.xml
      env:
        QRAM_APP_HMAC: ${{ secrets.QRAM_APP_HMAC }}
        QRAM_APP_GITHUB_APP_ID: ${{ secrets.QRAM_APP_GITHUB_APP_ID }}
        QRAM_APP_GITHUB_INSTALLATION_ID: ${{ secrets.QRAM_APP_GITHUB_INSTALLATION_ID }}
        QRAM_APP_GITHUB_PEM: ${{ secrets.QRAM_APP_GITHUB_PEM }}
        QRAM_WEBHOOK_URL: ""

    - uses: actions/upload-artifact@v3
      with:
        name: coverage-first
        path: coverage/
        if-no-files-found: error

  system-test-with-webhook:
    needs: ci
    runs-on: ubuntu-latest
    # hardcore system tests reconfigure github app webhook to use local ngrok tunnel,
    # so no more than one instance of those should be running at once
    concurrency: app-webhook-reconfiguration
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - run: |
        set -ex
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: download ngrok
      run: |
        set -ex
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar -xf ngrok-v3-stable-linux-amd64.tgz
        chmod +x ngrok
        ./ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}
    - name: system tests (B)
      run: |
        set -ex
        ./ngrok http 8888 &
        sleep 5
        URL=$(scripts/ngrok-public-url.py)

        echo "QRAM_WEBHOOK_URL=${URL}/webhook" > .env
        pytest \
          -o log_cli=1 \
          --log-cli-level=DEBUG \
          --log-cli-format='%(asctime)s %(levelname)-6s :: %(name)-25s :: %(message)s' \
          test/system/ \
          -m sysB \
          --cov \
          --cov-report xml
        mkdir coverage
        mv coverage.xml coverage/system.b.xml
      env:
        QRAM_APP_HMAC: ${{ secrets.QRAM_APP_HMAC }}
        QRAM_APP_GITHUB_APP_ID: ${{ secrets.QRAM_APP_GITHUB_APP_ID }}
        QRAM_APP_GITHUB_INSTALLATION_ID: ${{ secrets.QRAM_APP_GITHUB_INSTALLATION_ID }}
        QRAM_APP_GITHUB_PEM: ${{ secrets.QRAM_APP_GITHUB_PEM }}
    - uses: actions/upload-artifact@v3
      with:
        name: coverage-second
        path: coverage/
        if-no-files-found: error


  # upload coverage only if everything succeeds, to avoid weird temporary results when part of
  # tests fail between PR updates
  codecov:
    needs:
      - ci
      - system-test-with-webhook
    # without `always()` will skip if system is skipped; see:
    # - https://github.com/actions/runner/issues/491
    # - https://stackoverflow.com/questions/69354003
    if: |
      always() &&
      needs.ci.result == 'success' && (
        needs.system-test-with-webhook.result == 'success'
        || needs.system-test-with-webhook.result == 'skipped'
      )
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download 1st part of coverage
      uses: actions/download-artifact@v3
      with:
        name: coverage-first
    - name: Download 2nd part of coverage
      uses: actions/download-artifact@v3
      if: needs.system-test-with-webhook.result == 'success'
      with:
        name: coverage-second

    - name: Upload unit
      uses: codecov/codecov-action@v3
      with:
        files: unit.xml
        fail_ci_if_error: true
        flags: unit
    - name: Upload integration
      uses: codecov/codecov-action@v3
      with:
        files: integration.xml
        fail_ci_if_error: true
        flags: integration
    - name: Upload system
      uses: codecov/codecov-action@v3
      if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      with:
        files: system.a.xml, system.b.xml
        fail_ci_if_error: true
        flags: system
